"""The deterministic compliance engine.

This is the FINAL AUTHORITY on pass/fail. No LLM is involved in any compliance
decision. Given a normalized ``SecurityModel`` and a list of ``Rule`` objects,
it produces one ``Finding`` per control plus an ``AuditSummary``. Explanations
are templated (deterministic), never generated by a model.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

from app.compliance.operators import describe_expected, describe_observed, evaluate
from app.compliance.rules_loader import Rule, load_rules
from app.core.types import Finding, Severity, Status
from app.normalization.model import SecurityModel


@dataclass
class AuditSummary:
    total: int = 0
    passed: int = 0
    failed: int = 0
    warnings: int = 0
    not_applicable: int = 0
    critical: int = 0  # subset of failed with CRITICAL severity
    score: float = 0.0  # compliance percentage over evaluated (non-N/A) controls
    by_severity: Dict[str, int] = field(default_factory=dict)
    by_category: Dict[str, Dict[str, int]] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "total": self.total,
            "passed": self.passed,
            "failed": self.failed,
            "warnings": self.warnings,
            "not_applicable": self.not_applicable,
            "critical": self.critical,
            "score": self.score,
            "by_severity": dict(self.by_severity),
            "by_category": {k: dict(v) for k, v in self.by_category.items()},
        }


def _build_explanation(rule: Rule, status: Status, observed: str, expected: str) -> str:
    if status == Status.PASS:
        return f"{rule.title}: compliant. Observed {observed}."
    if status == Status.WARNING:
        return (
            f"{rule.title}: could not be confirmed from the configuration. "
            f"{rule.rationale} Expected {expected}; observed {observed}."
        )
    if status == Status.NOT_APPLICABLE:
        return f"{rule.title}: not applicable to this device."
    # FAIL
    return (
        f"{rule.title}: non-compliant. {rule.rationale} "
        f"Expected {expected}; observed {observed}."
    )


def evaluate_control(model: SecurityModel, rule: Rule) -> Finding:
    raw_value = model.get(rule.field)
    expected = describe_expected(rule.op, rule.value)

    if raw_value is None:
        status = rule.on_missing
        severity = Severity.INFO if status == Status.PASS else rule.severity
        observed = describe_observed(rule.field, None)
    else:
        passed = evaluate(rule.op, raw_value, rule.value)
        status = Status.PASS if passed else Status.FAIL
        severity = Severity.INFO if passed else rule.severity
        observed = describe_observed(rule.field, raw_value)

    return Finding(
        control_id=rule.id,
        title=rule.title,
        category=rule.category,
        framework=rule.framework,
        status=status,
        severity=severity,
        rationale=rule.rationale,
        explanation=_build_explanation(rule, status, observed, expected),
        evidence=model.evidence_for(rule.field),
        normalized_field=rule.field,
        expected=expected,
        observed=observed,
    )


def summarize(findings: List[Finding]) -> AuditSummary:
    summary = AuditSummary(total=len(findings))
    for f in findings:
        summary.by_severity[f.severity.value] = summary.by_severity.get(f.severity.value, 0) + 1
        cat = summary.by_category.setdefault(
            f.category, {"passed": 0, "failed": 0, "warnings": 0}
        )
        if f.status == Status.PASS:
            summary.passed += 1
            cat["passed"] += 1
        elif f.status == Status.FAIL:
            summary.failed += 1
            cat["failed"] += 1
            if f.severity == Severity.CRITICAL:
                summary.critical += 1
        elif f.status == Status.WARNING:
            summary.warnings += 1
            cat["warnings"] += 1
        elif f.status == Status.NOT_APPLICABLE:
            summary.not_applicable += 1

    evaluated = summary.passed + summary.failed + summary.warnings
    summary.score = round(summary.passed / evaluated * 100, 1) if evaluated else 0.0
    return summary


def evaluate_model(
    model: SecurityModel, rules: Optional[List[Rule]] = None
) -> tuple[List[Finding], AuditSummary]:
    rules = rules if rules is not None else load_rules()
    findings = [evaluate_control(model, rule) for rule in rules]
    # order: open findings first, by severity (critical -> low), then by control id
    findings.sort(
        key=lambda f: (
            0 if f.is_open else 1,
            -f.severity.rank,
            f.control_id,
        )
    )
    return findings, summarize(findings)
